# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoLayoutTest' do

  pod 'SDAutoLayout' , '~> 2.1.3'
  target 'AutoLayoutTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutoLayoutTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
